language: haskell
ghc: 7.8
install:
  - "cabal install --enable-tests --dry-run -v3"
  - "travis_retry cabal install --only-dependencies --force-reinstalls --enable-tests --enable-library-coverage"
script:
  - "cabal test --jobs=1"
after_script:
  - "cabal install --force-reinstalls hpc-coveralls"
  - "hpc-coveralls json-schema-generic-aeson-tests --exclude-dir=tests"
notifications:
  email:
    recipients:
      - adam@silk.co
    on_success: never
    on_failure: change
